-- User
CREATE TABLE IF NOT EXISTS public.users (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unique_id       uuid    NOT NULL,
    username        varchar(50)    NOT NULL,
    first_name      varchar(50)    NOT NULL,
    last_name       varchar(50)    NOT NULL,
    password_hash   text           NOT NULL,
    salt            text           NOT NULL,
    status          integer        NOT NULL,
    status_reason   varchar(200),
    role            integer        NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_users_unique_id
    ON public.users(unique_id);

-- RefreshToken
CREATE TABLE IF NOT EXISTS public.refresh_tokens (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash     varchar(88)  NOT NULL,
    expires_at     timestamp(3) NOT NULL,
    created_at     timestamp(3) NOT NULL,
    created_by_ip  varchar(45)  NOT NULL,
    revoked_at     timestamp(3),
    revoked_by_ip  varchar(45),
    replaced_by    varchar(88),
    user_id        integer       NOT NULL
);

ALTER TABLE public.refresh_tokens
ADD CONSTRAINT fk_refresh_tokens_user_id
    FOREIGN KEY(user_id) REFERENCES public.users(id) ON DELETE CASCADE;

CREATE INDEX ix_refresh_tokens_token_hash ON public.refresh_tokens(token_hash);
CREATE INDEX ix_refresh_tokens_user_id    ON public.refresh_tokens(user_id);
