CREATE TABLE IF NOT EXISTS public.users (
    id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unique_id       uuid    NOT NULL,
    username        varchar(50)    NOT NULL,
    first_name      varchar(50)    NOT NULL,
    last_name       varchar(50)    NOT NULL,
    password_hash   text           NOT NULL,
    salt            text           NOT NULL,
    status          integer        NOT NULL,
    status_reason   varchar(200),
    role            integer        NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_users_unique_id
    ON public.users(unique_id);